//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Paypro_Mobile.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangRS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangRS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Paypro_Mobile.Resources.LangRS", typeof(LangRS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YO`Q.
        /// </summary>
        public static string AlertNoText {
            get {
                return ResourceManager.GetString("AlertNoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string AlertOKText {
            get {
                return ResourceManager.GetString("AlertOKText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma&apos;lumotlar yangilanishida xato bo`ldi. Ma&apos;lumotlarni to`g`riligidan amin bo`ling..
        /// </summary>
        public static string AlertSaveFailMessage {
            get {
                return ResourceManager.GetString("AlertSaveFailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ma&apos;lumotlar muvaffaqiyatli qayd etildi..
        /// </summary>
        public static string AlertSaveSuccessMessage {
            get {
                return ResourceManager.GetString("AlertSaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HA.
        /// </summary>
        public static string AlertYesText {
            get {
                return ResourceManager.GetString("AlertYesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Login.
        /// </summary>
        public static string AutoLoginText {
            get {
                return ResourceManager.GetString("AutoLoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastik (bank) kartasi raqami:.
        /// </summary>
        public static string CardPageCardNumberInput {
            get {
                return ResourceManager.GetString("CardPageCardNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastik (bank) Kartalari Bo`limi.
        /// </summary>
        public static string CardPageSubTitle {
            get {
                return ResourceManager.GetString("CardPageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastik (bank) Kartalari.
        /// </summary>
        public static string CardPageTitle {
            get {
                return ResourceManager.GetString("CardPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yozuvni o`zgartirish.
        /// </summary>
        public static string ChangeLanguageText {
            get {
                return ResourceManager.GetString("ChangeLanguageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iltimos bo`sh joyni to`ldiring..
        /// </summary>
        public static string ErrorMessageEmpty {
            get {
                return ResourceManager.GetString("ErrorMessageEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yozgan summangiz minimumdan past!.
        /// </summary>
        public static string ErrorMessageMinMoney {
            get {
                return ResourceManager.GetString("ErrorMessageMinMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hisob raqamini kiriting:.
        /// </summary>
        public static string GlobalAccountNumberText {
            get {
                return ResourceManager.GetString("GlobalAccountNumberText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orqaga.
        /// </summary>
        public static string GlobalBtnBackText {
            get {
                return ResourceManager.GetString("GlobalBtnBackText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyingsi.
        /// </summary>
        public static string GlobalBtnContinueText {
            get {
                return ResourceManager.GetString("GlobalBtnContinueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summani yozing.
        /// </summary>
        public static string GlobalInputMoneyText {
            get {
                return ResourceManager.GetString("GlobalInputMoneyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plastik (bank) kartalari.
        /// </summary>
        public static string HomePageCard {
            get {
                return ResourceManager.GetString("HomePageCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP telefoniya.
        /// </summary>
        public static string HomePageIPTelefoniya {
            get {
                return ResourceManager.GetString("HomePageIPTelefoniya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Televedeniya (IP TV).
        /// </summary>
        public static string HomePageIPTV {
            get {
                return ResourceManager.GetString("HomePageIPTV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet provayderlari (Wi-Fi).
        /// </summary>
        public static string HomePageISS {
            get {
                return ResourceManager.GetString("HomePageISS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil aloqa.
        /// </summary>
        public static string HomePageMobile {
            get {
                return ResourceManager.GetString("HomePageMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunal xizmatlar.
        /// </summary>
        public static string HomePagePublicServices {
            get {
                return ResourceManager.GetString("HomePagePublicServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xush kelibsiz!.
        /// </summary>
        public static string HomePageWelcomeMsg {
            get {
                return ResourceManager.GetString("HomePageWelcomeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karta raqami xato! Iltimos karta raqamini tog’ri yozing.
        /// </summary>
        public static string InvalidCardErrorText {
            get {
                return ResourceManager.GetString("InvalidCardErrorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Telefoniya Bo`limi.
        /// </summary>
        public static string IPPhonePageSubTitle {
            get {
                return ResourceManager.GetString("IPPhonePageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Telefoniya.
        /// </summary>
        public static string IPPhonePageTitle {
            get {
                return ResourceManager.GetString("IPPhonePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provaderni tanglang:.
        /// </summary>
        public static string IPPhoneSelectProvider {
            get {
                return ResourceManager.GetString("IPPhoneSelectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Televedeniya (IP TV) Bo`limi.
        /// </summary>
        public static string IPTVPageSubTitle {
            get {
                return ResourceManager.GetString("IPTVPageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Televedeniya (IP TV).
        /// </summary>
        public static string IPTVPageTitle {
            get {
                return ResourceManager.GetString("IPTVPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provayderni tanglang:.
        /// </summary>
        public static string IPTVSelectProviderText {
            get {
                return ResourceManager.GetString("IPTVSelectProviderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provayderni tanglang:.
        /// </summary>
        public static string ISSSelectProviderText {
            get {
                return ResourceManager.GetString("ISSSelectProviderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Provayderlar (Wi-Fi).
        /// </summary>
        public static string ISSSubTitle {
            get {
                return ResourceManager.GetString("ISSSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Provayderlar (Wi-Fi).
        /// </summary>
        public static string ISSTitle {
            get {
                return ResourceManager.GetString("ISSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirish.
        /// </summary>
        public static string LoginBtnText {
            get {
                return ResourceManager.GetString("LoginBtnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tizimga Kirmasdan Davom Etish.
        /// </summary>
        public static string LoginBtnWithoutLogin {
            get {
                return ResourceManager.GetString("LoginBtnWithoutLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail yoki parol xatoli!.
        /// </summary>
        public static string LoginFailText {
            get {
                return ResourceManager.GetString("LoginFailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avval tizimga kirish zarur, tizimga kirishni istaysizmi?.
        /// </summary>
        public static string LoginNeededMessage {
            get {
                return ResourceManager.GetString("LoginNeededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parol:.
        /// </summary>
        public static string LoginPassText {
            get {
                return ResourceManager.GetString("LoginPassText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoziroq royxatdan o`tish!.
        /// </summary>
        public static string LoginRegisterText {
            get {
                return ResourceManager.GetString("LoginRegisterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirish yoki davom etish.
        /// </summary>
        public static string LoginSubTitle {
            get {
                return ResourceManager.GetString("LoginSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kirish muvofoqiyatli!.
        /// </summary>
        public static string LoginSuccessText {
            get {
                return ResourceManager.GetString("LoginSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login yoki emailingiz:.
        /// </summary>
        public static string LoginUsernameText {
            get {
                return ResourceManager.GetString("LoginUsernameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayProUz.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon raqamini yozing:.
        /// </summary>
        public static string MobilePageInputPhone {
            get {
                return ResourceManager.GetString("MobilePageInputPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil Aloqalar Bo`limi.
        /// </summary>
        public static string MobilePageSubTitle {
            get {
                return ResourceManager.GetString("MobilePageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobil Aloqalar.
        /// </summary>
        public static string MobilePageTitle {
            get {
                return ResourceManager.GetString("MobilePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To`lash!.
        /// </summary>
        public static string PaymentBtnCompleteText {
            get {
                return ResourceManager.GetString("PaymentBtnCompleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To`lanadigan pul.
        /// </summary>
        public static string PaymentPagePaid {
            get {
                return ResourceManager.GetString("PaymentPagePaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To`lov sahifasi.
        /// </summary>
        public static string PaymentPageSubTitle {
            get {
                return ResourceManager.GetString("PaymentPageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Payment.
        /// </summary>
        public static string PaymentPageTitle {
            get {
                return ResourceManager.GetString("PaymentPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiritgan ma&apos;lumotlaringizni tekshiring. Agar xatolik bo`lsa orqaga qaytib to`g`irlang!.
        /// </summary>
        public static string PaymentPageWarningText {
            get {
                return ResourceManager.GetString("PaymentPageWarningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tanglang....
        /// </summary>
        public static string PickerPlaceHolderText {
            get {
                return ResourceManager.GetString("PickerPlaceHolderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viloyatni Tanlang:.
        /// </summary>
        public static string PublicServicesPageSelectCity {
            get {
                return ResourceManager.GetString("PublicServicesPageSelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xududni Tanlang:.
        /// </summary>
        public static string PublicServicesPageSelectCounty {
            get {
                return ResourceManager.GetString("PublicServicesPageSelectCounty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xizmat Turu:.
        /// </summary>
        public static string PublicServicesPageServiceTypeText {
            get {
                return ResourceManager.GetString("PublicServicesPageServiceTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunal Xizmatlar Bo`limi.
        /// </summary>
        public static string PublicServicesPageSubTitle {
            get {
                return ResourceManager.GetString("PublicServicesPageSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommunal Xizmatlar.
        /// </summary>
        public static string PublicServicesPageTitle {
            get {
                return ResourceManager.GetString("PublicServicesPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aloqa.
        /// </summary>
        public static string TabPageContactTitle {
            get {
                return ResourceManager.GetString("TabPageContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To`lovlarim.
        /// </summary>
        public static string TabPagePastOrdersTitle {
            get {
                return ResourceManager.GetString("TabPagePastOrdersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string TabPageProfileTitle {
            get {
                return ResourceManager.GetString("TabPageProfileTitle", resourceCulture);
            }
        }
    }
}
